import React, { useEffect, useState } from 'react';
import { useForm } from '@formspree/react';
import { createRoot } from 'react-dom/client';
import type { FormEvent } from 'react';
import { capabilities, projects } from './projects';
import type { PortfolioImage, Project } from './projects';
import './styles.css';
import { selectedWork } from './selectedWork';

function Orbit({ className = '' }: { className?: string }) { return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="22" stroke="currentColor" strokeWidth="2"/><ellipse cx="50" cy="50" rx="47" ry="17" transform="rotate(-40 50 50)" stroke="currentColor" strokeWidth="2"/></svg>; }
function Header() { const [open, setOpen] = useState(false); return <header className="header"><a className="wordmark" href="/" aria-label="Concrete Orbit home">concrete orbit<span>®</span></a><button className="menu-button" aria-expanded={open} aria-controls="navigation" onClick={() => setOpen(!open)}>{open ? 'Close −' : 'Menu +'}</button><nav id="navigation" className={open ? 'navigation open' : 'navigation'} aria-label="Main navigation"><a href="/#work" onClick={() => setOpen(false)}>Selected work</a><a href="/#studio" onClick={() => setOpen(false)}>The studio</a><a className="nav-cta" href="/#contact" onClick={() => setOpen(false)}>Let’s talk <span>↗</span></a></nav></header>; }
function ImageFrame({ image, tone = 'hero-tone', label, priority = false }: { image?: PortfolioImage | null; tone?: string; label: string; priority?: boolean }) { return image ? <img className="portfolio-image" src={image.src} srcSet={image.srcSet} sizes="(max-width: 700px) 100vw, 90vw" alt={image.alt} width={image.width} height={image.height} loading={priority ? 'eager' : 'lazy'} decoding="async"/> : <div className={`image-placeholder ${tone}`} role="img" aria-label={`${label} — image placeholder, final imagery to be supplied`}><span className="frame-corner top-left"/><span className="frame-corner bottom-right"/><span className="placeholder-cross">+</span><div className="placeholder-caption"><span>IMAGE PLACEHOLDER</span></div></div>; }
function Work() {
  return <section id="work" className="work section-pad curated-work">
    <div className="section-heading"><div><span className="lab-index">01 / SELECTED WORK</span><h2>Campaign systems,<br/>built through image.</h2></div><p className="section-note">PRODUCT / CAMPAIGN / IMAGE-MAKING<br/>WASHINGTON, DC · WORLDWIDE</p></div>
    <div className="curated-grid">{selectedWork.map((selection, i) => (
      <a className={`curated-card curated-card-${i + 1} curated-${selection.size}`} href={`/work/${selection.slug}`} key={selection.slug}>
        <div className="curated-image"><img className="portfolio-image" src={selection.image.src} srcSet={selection.image.srcSet} sizes={selection.size === 'large' ? '90vw' : selection.size === 'medium' ? '(max-width: 700px) 85vw, 60vw' : '(max-width: 700px) 72vw, 30vw'} width={selection.image.width} height={selection.image.height} alt={selection.image.alt} loading="lazy" decoding="async"/></div>
        <div className="curated-caption"><span className="project-number">{String(i + 1).padStart(2, '0')}</span><div><h3>{selection.title}</h3><p>{selection.subtitle}</p></div><span aria-hidden="true">↗</span></div>
      </a>
    ))}</div>
  </section>;
}
function Studio() { return <><section id="studio" className="philosophy section-pad"><span className="eyebrow">OUR PHILOSOPHY</span><h2>THE IDEA DETERMINES<br/>HOW WE MAKE<br/>THE <em>IMAGE.</em><Orbit/></h2><div className="philosophy-bottom"><p>The creative idea comes first. Photography, CGI, 3D and compositing are ways to bring it to life. The production method follows the vision.</p></div></section><section className="why section-pad"><div className="studio-intro"><span className="eyebrow">THE STUDIO</span><h2>A smaller studio.<br/>A bigger creative range.</h2><p>Direct collaboration with brands and creative teams, from concept through final image.</p></div><div className="principles">{[['DIRECT COLLABORATION','Work directly with the creative lead.'],['FLEXIBLE PRODUCTION','The image determines the production approach.'],['DISTINCTIVE VISUAL THINKING','Imagery people remember. A visual world of your own.']].map(([title, copy], i) => <div className="principle" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section><section className="founder section-pad"><div className="founder-label"><Orbit/><img className="founder-image-placeholder" src="/images/simon-founder-portrait-1200.webp" srcSet="/images/simon-founder-portrait-800.webp 800w, /images/simon-founder-portrait-1200.webp 1200w" sizes="(max-width: 600px) 230px, 280px" width={3915} height={3910} alt="Simon Jackson, Founder and Creative Director of Concrete Orbit" loading="lazy" decoding="async"/><span className="eyebrow">FOUNDER / CREATIVE DIRECTOR</span></div><div><h2>One creative vision.<br/>From start to finish.</h2><p>An independent studio led directly by its creative director, with close attention to every detail — from striking hero imagery to intricate macro worlds.</p><div className="founder-name">SIMON JACKSON<span>Founder + Creative Director</span><p className="founder-approach">My approach grew from years of experimenting with light, composition and image-making. Today, that perspective shapes the studio and the work we create for brands.</p></div></div></section><section className="partners section-pad"><span className="eyebrow">COLLABORATION</span><h2>For brands, agencies<br/>& creative teams.</h2><div className="partner-options"><div><span className="small-label">FROM THE FIRST IDEA</span><p>A distinctive visual world for your product, from campaign concept through final image.</p></div><div><span className="small-label">PART OF YOUR TEAM</span><p>We join your creative team as a visual production partner to bring an existing direction to life.</p></div></div><div className="capabilities"><span className="eyebrow">OUR CAPABILITIES</span><p>{capabilities.join(' · ')}</p></div></section></>; }
function Contact() { const [state, handleSubmit] = useForm('xbgjzjge'); const succeeded = state.succeeded || Boolean(state.result); return <section id="contact" className="contact section-pad"><div className="contact-heading"><h2>START A<br/>PROJECT <span>↗</span></h2><p>Tell us what you’re launching, what you’re looking to create and when you need it.</p></div><form onSubmit={handleSubmit} encType="multipart/form-data"><div className="form-row"><label>Name <span>*</span><input name="Name" autoComplete="name" required placeholder="Your name"/></label><label>Company<input name="Company" autoComplete="organization" placeholder="Brand or agency"/></label></div><label>Email <span>*</span><input name="Email" type="email" autoComplete="email" required placeholder="you@company.com"/></label><label>What are you looking to create? <span>*</span><textarea name="Project" required rows={3} placeholder="A little about your project…"/></label><div className="form-row"><label>When do you need it?<input name="Timeline" placeholder="Your ideal timeline"/></label><label>Estimated budget<select name="Budget" defaultValue=""><option value="" disabled>Select a range</option><option>Under $5,000</option><option>$5,000–$10,000</option><option>$10,000–$25,000</option><option>$25,000–$50,000</option><option>$50,000+</option><option>Let’s discuss</option></select></label></div><label className="upload-label">Reference / upload<input type="file" name="reference" accept="image/*,.pdf"/><small>Optional image or PDF. Formspree file uploads may require a paid plan.</small></label><p className="form-note">Your inquiry will be sent securely through Formspree.</p><button className="submit" type="submit" disabled={state.submitting}>{state.submitting ? 'SENDING…' : 'START A PROJECT'} <span>→</span></button>{succeeded && <p className="form-status" role="status">Thank you — your inquiry has been received.</p>}{state.errors && !succeeded && <p className="form-status" role="alert">Something went wrong. Please try again.</p>}</form></section>; }function Footer() { return <footer className="section-pad"><div className="footer-top"><a className="wordmark" href="/">concrete orbit<span>®</span></a><p>Based in Washington, DC.<br/>Working worldwide.</p><a href="#top">Back to top ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Concrete Orbit</span><a href="https://www.instagram.com/concreteorbitvisuals/" target="_blank" rel="noopener noreferrer" aria-label="Concrete Orbit on Instagram (opens in a new tab)" style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 24, height: 24}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true" focusable="false"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a></div></footer>; }

function Home() {
  return <>
    <section className="hero section-pad fullbleed-hero">
      <div className="hero-image">
        <picture className="homepage-hero-photo">
          <source media="(max-width: 800px)" srcSet="/images/trace-hero-spacious-mobile-640.webp 640w, /images/trace-hero-spacious-mobile-960.webp 960w" sizes="100vw"/>
          <img className="portfolio-image" src="/images/trace-hero-spacious-1920.webp" srcSet="/images/trace-hero-spacious-1280.webp 1280w, /images/trace-hero-spacious-1920.webp 1920w, /images/trace-hero-spacious-2560.webp 2560w" sizes="100vw" width={5504} height={3072} alt="Trace 40,000 Volts electrolyte concentrate bottle covered in water droplets, lit in deep blue against a black background." loading="eager" fetchPriority="high" decoding="async"/>
        </picture>
        <div className="fullbleed-hero-copy">
          <p className="fullbleed-hero-brand"><span>CONCRETE ORBIT</span></p>
          <h1>Give your product<br/>a presence of its own.</h1>
          <p className="fullbleed-hero-description">Campaign and product imagery that helps beauty, wellness and lifestyle brands stand out.</p>
        </div>
        <div className="hero-axis" aria-hidden="true"><span>IMAGE / MATTER / LIGHT</span><span>SCROLL  ↓</span></div>
      </div>
    </section>
    <Work/><Studio/><Contact/>
  </>;
}function ProjectPage({ project }: { project: Project }) { return <><section className="project-detail section-pad curated-project"><a className="back-link" href="/#work">← PROJECT INDEX</a><div className="detail-heading"><div><span className="eyebrow">CAMPAIGN / PRODUCT</span><h1>{project.name}</h1></div><p>{project.brand}</p></div><ImageFrame image={project.cover} tone={project.tone} label={`${project.name} / HERO`} priority/><div className="project-information"><div><span className="eyebrow">THE PROJECT</span><p>{project.description ?? 'Project description to be added. Approved project information and final imagery will appear here.'}</p></div><div><span className="eyebrow">SCOPE</span><p>Creative Direction<br/>Art Direction<br/>Photography<br/>CGI<br/>Compositing</p></div></div><div className="project-grid campaign-sequence">{project.gallery.length ? project.gallery.map((img, index) => <div className="project-frame" key={img.src}><span className="frame-index">FRAME / {String(index + 1).padStart(2, '0')}</span><ImageFrame image={img} label={img.alt}/></div>) : <><ImageFrame tone={project.tone} label="SUPPORTING IMAGE / 01"/><ImageFrame tone={project.tone} label="MACRO DETAIL / 02"/></>}</div><div className="project-end"><div><span className="eyebrow">NEED SOMETHING SIMILAR?</span><a href="/#contact">START A PROJECT →</a></div><a href="/#work">← PROJECT INDEX</a></div></section></>; }
function App() { const path = window.location.pathname.replace(/\/$/, '') || '/'; const project = projects.find(p => path === `/work/${p.slug}`); useEffect(() => { const title = project ? `${project.name} — Concrete Orbit` : path === '/' ? 'Concrete Orbit — Premium Product Imagery' : 'Page not found — Concrete Orbit'; document.title = title; document.querySelector('meta[property="og:title"]')?.setAttribute('content', title); if (project) document.querySelector('meta[name="description"]')?.setAttribute('content', `${project.name} for ${project.brand}. Explore the Concrete Orbit campaign and product imagery portfolio.`); }, [project, path]); return <><a className="skip-link" href="#main">Skip to content</a><div id="top"/><Header/><main id="main">{path === '/' ? <Home/> : project ? <ProjectPage project={project}/> : <section className="not-found section-pad"><span className="eyebrow">404 / OUT OF ORBIT</span><h1>Nothing here. Yet.</h1><a href="/">Return to the studio →</a></section>}</main><Footer/></>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
