import React, { useEffect, useState } from 'react';
import { useForm } from '@formspree/react';
import { createRoot } from 'react-dom/client';
import { capabilities, projects } from './projectData';
import type { PortfolioImage, Project } from './projectData';
import './styles.css';
import { selectedWork } from './selectedWork';

function Orbit({ className = '' }: { className?: string }) { return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="22" stroke="currentColor" strokeWidth="2"/><ellipse cx="50" cy="50" rx="47" ry="17" transform="rotate(-40 50 50)" stroke="currentColor" strokeWidth="2"/></svg>; }
function Header() { const [open, setOpen] = useState(false); return <header className="header"><a className="wordmark" href="/" aria-label="Concrete Orbit home">concrete orbit<span>®</span></a><button className="menu-button" aria-expanded={open} aria-controls="navigation" onClick={() => setOpen(!open)}>{open ? 'Close −' : 'Menu +'}</button><nav id="navigation" className={open ? 'navigation open' : 'navigation'} aria-label="Main navigation"><a href="/#work" onClick={() => setOpen(false)}>Selected work</a><a href="/#studio" onClick={() => setOpen(false)}>The studio</a><a className="nav-cta" href="/#contact" onClick={() => setOpen(false)}>Let’s talk <span>↗</span></a></nav></header>; }
function ImageFrame({ image, tone = 'hero-tone', label, priority = false }: { image?: PortfolioImage | null; tone?: string; label: string; priority?: boolean }) { return image ? <img className="portfolio-image" src={image.src} srcSet={image.srcSet} sizes="(max-width: 700px) 100vw, 90vw" alt={image.alt} width={image.width} height={image.height} loading={priority ? 'eager' : 'lazy'} decoding="async"/> : <div className={`image-placeholder ${tone}`} role="img" aria-label={`${label} — image placeholder, final imagery to be supplied`}><span className="frame-corner top-left"/><span className="frame-corner bottom-right"/><span className="placeholder-cross">+</span><div className="placeholder-caption"><span>IMAGE PLACEHOLDER</span></div></div>; }
function Work() {
  const [showHero, setShowHero] = useState(false);

  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const interval = window.setInterval(() => setShowHero(current => !current), 30000);
    return () => window.clearInterval(interval);
  }, []);

  return <section id="work" className="work section-pad curated-work">
    <div className="section-heading"><div><span className="lab-index">01 / SELECTED WORK</span><h2>Selected product<br/>campaigns.</h2></div><p className="section-note">HERO / DETAIL / COPY SPACE<br/>WASHINGTON, DC · WORLDWIDE</p></div>
    <div className="curated-grid">{selectedWork.map((selection, i) => (
      <a className={`curated-card curated-card-${i + 1} curated-${selection.size}`} href={`/work/${selection.slug}`} key={selection.slug}>
        <div className={`curated-image rotating-work-image${showHero ? ' show-alternate' : ''}`}>
          <img className="portfolio-image rotating-primary" src={selection.image.src} srcSet={selection.image.srcSet} sizes={selection.size === 'large' ? '90vw' : selection.size === 'medium' ? '(max-width: 700px) 85vw, 60vw' : '(max-width: 700px) 72vw, 30vw'} width={selection.image.width} height={selection.image.height} alt={selection.image.alt} loading="lazy" decoding="async"/>
          {selection.alternateImage && <img className="portfolio-image rotating-alternate" src={selection.alternateImage.src} srcSet={selection.alternateImage.srcSet} sizes="90vw" width={selection.alternateImage.width} height={selection.alternateImage.height} alt="" aria-hidden="true" loading="lazy" decoding="async"/>}
        </div>
        <div className="curated-caption"><span className="project-number">{String(i + 1).padStart(2, '0')}</span><div><h3>{selection.title}</h3><p>{selection.subtitle}</p></div><span aria-hidden="true">↗</span></div>
      </a>
    ))}</div>
  </section>;
}
function Studio() { return <><section id="studio" className="philosophy section-pad"><span className="eyebrow">HOW I WORK</span><h2>THE PRODUCT SETS<br/>THE DIRECTION.<br/><em>EVERY TIME.</em><Orbit/></h2><div className="philosophy-bottom"><p>I start with what the product should make someone feel. Then I choose the mix of practical photography, CGI and compositing that serves that idea.</p></div></section><section className="why section-pad"><div className="studio-intro"><span className="eyebrow">THE STUDIO</span><h2>One lead from<br/>brief to delivery.</h2><p>You work directly with me on concept, shot planning, production and finishing. That keeps the visual direction intact and the feedback loop short.</p></div><div className="principles">{[['BEFORE THE SHOOT','We define the audience, intended use and images the project needs.'],['DURING PRODUCTION','I shape the light, composition and material detail around the product.'],['AT DELIVERY','You receive finished images prepared for the formats agreed in the brief.']].map(([title, copy], i) => <div className="principle" key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></section><section className="founder section-pad"><div className="founder-label"><Orbit/><img className="founder-image-placeholder" src="/images/simon-founder-portrait-1200.webp" srcSet="/images/simon-founder-portrait-800.webp 800w, /images/simon-founder-portrait-1200.webp 1200w" sizes="(max-width: 600px) 230px, 280px" width={3915} height={3910} alt="Simon Jackson, Founder and Creative Director of Concrete Orbit" loading="lazy" decoding="async"/><span className="eyebrow">FOUNDER / CREATIVE DIRECTOR</span></div><div><h2>I make the work<br/>and lead the project.</h2><p>I’m Simon Jackson, the photographer and creative director behind Concrete Orbit.</p><div className="founder-name">SIMON JACKSON<span>Founder + Creative Director</span><p className="founder-approach">I built the studio around a hands-on process: developing the visual idea, photographing the product and carrying the image through its final finish.</p></div></div></section><section className="partners section-pad"><span className="eyebrow">WAYS TO WORK TOGETHER</span><h2>Bring the brief—or<br/>bring the question.</h2><div className="partner-options"><div><span className="small-label">DEVELOP THE DIRECTION</span><p>I can shape the concept, mood, composition and shot plan around your product or launch.</p></div><div><span className="small-label">EXECUTE YOUR DIRECTION</span><p>If the art direction is already set, I can carry it through production, compositing and final files.</p></div></div><div className="capabilities"><span className="eyebrow">CAPABILITIES</span><p>{capabilities.join(' · ')}</p></div></section></>; }
function Contact() { const [state, handleSubmit] = useForm('xbgjzjge'); const succeeded = state.succeeded || Boolean(state.result); return <section id="contact" className="contact section-pad"><div className="contact-heading"><h2>START A<br/>PROJECT <span>↗</span></h2><p>Tell me about the product, where the images will be used, how many you need and your launch date.</p></div><form onSubmit={handleSubmit} encType="multipart/form-data"><div className="form-row"><label>Name <span>*</span><input name="Name" autoComplete="name" required placeholder="Your name"/></label><label>Company<input name="Company" autoComplete="organization" placeholder="Brand or agency"/></label></div><label>Email <span>*</span><input name="Email" type="email" autoComplete="email" required placeholder="you@company.com"/></label><label>What are you looking to create? <span>*</span><textarea name="Project" required rows={3} placeholder="Product, image count, intended use and anything else I should know…"/></label><div className="form-row"><label>When do you need it?<input name="Timeline" placeholder="Launch date or ideal timeline"/></label><label>Estimated budget<select name="Budget" defaultValue=""><option value="" disabled>Select a range</option><option>Under $5,000</option><option>$5,000–$10,000</option><option>$10,000–$25,000</option><option>$25,000–$50,000</option><option>$50,000+</option><option>Let’s discuss</option></select></label></div><label className="upload-label">Reference / upload<input type="file" name="reference" accept="image/*,.pdf"/><small>Optional. Add an image or PDF if it helps explain the project.</small></label><button className="submit" type="submit" disabled={state.submitting}>{state.submitting ? 'SENDING…' : 'SEND INQUIRY'} <span>→</span></button>{succeeded && <p className="form-status" role="status">Thanks — your note is in. I’ll be in touch soon.</p>}{state.errors && !succeeded && <p className="form-status" role="alert">Something went wrong. Please try again.</p>}</form></section>; }function Footer() { return <footer className="section-pad"><div className="footer-top"><a className="wordmark" href="/">concrete orbit<span>®</span></a><p>Based in Washington, DC.<br/>Working worldwide.</p><a href="#top">Back to top ↑</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Concrete Orbit</span><a href="https://www.instagram.com/concreteorbitvisuals/" target="_blank" rel="noopener noreferrer" aria-label="Concrete Orbit on Instagram (opens in a new tab)" style={{display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 24, height: 24}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true" focusable="false"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a></div></footer>; }

function Home() {
  return <>
    <section className="hero section-pad fullbleed-hero">
      <div className="hero-image">
        <picture className="homepage-hero-photo">
          <source media="(max-width: 800px)" srcSet="/images/trace-hero-spacious-mobile-640.webp 640w, /images/trace-hero-spacious-mobile-960.webp 960w" sizes="100vw"/>
          <img className="portfolio-image" src="/images/trace-hero-spacious-1920.webp" srcSet="/images/trace-hero-spacious-1280.webp 1280w, /images/trace-hero-spacious-1920.webp 1920w, /images/trace-hero-spacious-2560.webp 2560w" sizes="100vw" width={5504} height={3072} alt="Trace 40,000 Volts electrolyte concentrate bottle covered in water droplets, lit in deep blue against a black background." loading="eager" fetchPriority="high" decoding="async"/>
        </picture>
        <div className="fullbleed-hero-copy">
          <p className="fullbleed-hero-brand"><span>CONCRETE ORBIT</span></p>
          <h1>Give your product<br/>a presence of its own.</h1>
          <p className="fullbleed-hero-description">Concept-led campaign and product imagery for beauty, wellness and lifestyle brands—from art direction through final retouching.</p>
        </div>
        <div className="hero-axis" aria-hidden="true"><span>IMAGE / MATTER / LIGHT</span><span>SCROLL  ↓</span></div>
      </div>
    </section>
    <section className="featured-strip section-pad" aria-label="Brands featured in the portfolio"><span>FEATURED WORK</span><p>HARRY’S · METHOD · TRACE · SPORTS RESEARCH · CREMO</p></section>
    <Work/><Studio/><Contact/>
  </>;
}function ProjectPage({ project }: { project: Project }) { return <><section className="project-detail section-pad curated-project"><a className="back-link" href="/#work">← PROJECT INDEX</a><div className="detail-heading"><div><span className="eyebrow">PORTFOLIO / PRODUCT IMAGE SERIES</span><h1>{project.name}</h1></div><p>{project.brand}</p></div><ImageFrame image={project.cover} tone={project.tone} label={`${project.name} / HERO`} priority/><div className="project-information"><div><span className="eyebrow">THE BRIEF</span><p>{project.brief}</p></div><div><span className="eyebrow">VISUAL APPROACH</span><p>{project.approach}</p></div><div><span className="eyebrow">STUDIO ROLE</span><p>{project.services.join(' · ')}</p></div><div><span className="eyebrow">IMAGE SET</span><p>{project.deliverables}</p></div></div><div className="project-grid campaign-sequence">{project.gallery.length ? project.gallery.map((img, index) => <div className="project-frame" key={img.src}><span className="frame-index">FRAME / {String(index + 1).padStart(2, '0')}</span><ImageFrame image={img} label={img.alt}/></div>) : <><ImageFrame tone={project.tone} label="SUPPORTING IMAGE / 01"/><ImageFrame tone={project.tone} label="MACRO DETAIL / 02"/></>}</div><div className="project-end"><div><span className="eyebrow">HAVE A PRODUCT IN MIND?</span><a href="/#contact">START A PROJECT →</a></div><a href="/#work">← PROJECT INDEX</a></div></section></>; }
function App() { const path = window.location.pathname.replace(/\/$/, '') || '/'; const project = projects.find(p => path === `/work/${p.slug}`); useEffect(() => { const title = project ? `${project.name} — Concrete Orbit` : path === '/' ? 'Concrete Orbit — Premium Product Imagery' : 'Page not found — Concrete Orbit'; document.title = title; document.querySelector('meta[property="og:title"]')?.setAttribute('content', title); if (project) document.querySelector('meta[name="description"]')?.setAttribute('content', `${project.name}: ${project.approach}`); }, [project, path]); return <><a className="skip-link" href="#main">Skip to content</a><div id="top"/><Header/><main id="main">{path === '/' ? <Home/> : project ? <ProjectPage project={project}/> : <section className="not-found section-pad"><span className="eyebrow">404 / OUT OF ORBIT</span><h1>Nothing here. Yet.</h1><a href="/">Return to the studio →</a></section>}</main><Footer/></>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
